# Generated by Django 5.2.5 on 2025-08-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, unique=True)),
                ('confirmed', models.FloatField(default=0)),
                ('active', models.FloatField(default=0)),
                ('recovered', models.FloatField(default=0)),
                ('deaths', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'COVID Data',
                'verbose_name_plural': 'COVID Data',
                'db_table': 'c19',
                'ordering': ['-confirmed'],
            },
        ),
    ]
